### ISSUE TITLE
User Registration Bug

### ISSUE THREAD

**Issue by puzzledsean** [Bostonhacks/headstart#18]
# To replicate the bug:

1. User registers with email and password 
   (i.e. email john@yahoo.com, p/w 123456)
2. User says "no" to allowing MyMLH to authorize and cancels or just simply clicks the back button to go back to BostonHacks website
3. User can now click "Login" with any password (even if it doesn't meet password requirements) and get taken to MyMLH authorization
   (i.e. email john@yahoo.com, p/w 1 --> a blank password can also get through as well)
4. User also cannot register anymore either; they get an error: "That email is already taken"

**Comment by puzzledsean** [comment]
## Login Bug has been updated and fixed.

# There is still an issue with registering, however. To replicate:
1. User registers with email and password 
   (i.e. email john@yahoo.com, p/w 123456789)
2. User clicks "Logout" while being redirected to MyMLH
4. User cannot register; they get an error: "That email is already taken"

**Comment by NicoHinderling** [comment]
This is because they're already created an account. They are able to simply login again and the registration flow will start anew :)
