### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by a--hoang** [Bostonhacks/headstart#2]
Add eslint to this project

**Comment by NicoHinderling** [comment]
I wanna try https://github.com/feross/standard

will let you know how it works 😎 has more stars on github and im a ho for stars

**Comment by a--hoang** [comment]
I like it a lot. it's v simple. GL!

**Comment by NicoHinderling** [comment]
v lit. I'll close this once all the files pass the lint

**Comment by NicoHinderling** [comment]
:)
