### ISSUE TITLE
Where to add sponsor doc?

### ISSUE THREAD

**Issue by a--hoang** [Bostonhacks/headstart#5]
Currently, the sponsor button on the landing page doesn't work. We should fix this. I have some options:

1) commit the sponsor doc pdf to this repo, which isn't exactly the best practice, esp if we're treating this as a real OSS project

2) put the sponsor doc pdf somewhere online (dropbox, s3, etc) and link to it. bonus points - link is a .env setting.

3) something else i.e. creating a folder for static pdf assets and sticking it there

**Comment by NicoHinderling** [comment]
done
