### ISSUE TITLE
Make site MLH - compatible

### ISSUE THREAD

**Issue by a--hoang** [Bostonhacks/headstart#6]
To make the site MLH compatible, we need to:

1) List the code of conduct somewhere on the landing page
2) Add a checkbox and links to the code of conduct and privacy policy in the registration flow (is this taken care of by mymlh already?)

Code of Conduct: [HERE](https://static.mlh.io/docs/mlh-code-of-conduct.pdf)
Privacy: [HERE](https://mlh.io/privacy)

**Comment by a--hoang** [comment]
@NicoHinderling this is taken care of by MyMLH right? Closing.

**Comment by NicoHinderling** [comment]
Yes, and the code of conduct is on the homepage 🥇
